netwObserver/analyse/urls.py
from django.conf.urls import patterns, url

from analyse import views

urlpatterns = patterns('',
	url(r'^$', views.general),
	url(r'general/', views.general, name='general'),
	
	url(r'wifi/ap', views.wifiAP, name='wifiAP'),
	url(r'wifi/rap', views.wifiRAP, name='wifiRAP'),
	url(r'wifi/users', views.wifiUsers, name='wifiUsers'),
	url(r'wifi/probes', views.wifiProbes, name='wifiProbes'),
	url(r'wifi/', views.wifiOverview, name='wifi'),

	url(r'controller/', views.controller, name='controller'),
	
	url(r'dhcp/alerts', views.dhcpAlerts, name='dhcpalerts'),
	url(r'dhcp/graph', views.dhcpGraph, name='dhcpgraph'),
	url(r'dhcp/', views.dhcpAlerts, name='dhcp'),
	

	url(r'radius/', views.radius, name='radius'),
)

netwObserver/netwObserver/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
	# Examples:
    url(r'^$', 'netwObserver.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^gatherer/', include('gatherer.urls')),
    url(r'^analysis/', include('analyse.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

netwObserver/analyse/models.py
from django.db import models

# Create your models here.

netwObserver/gatherer/models.py
from django.db import models
from custom import macField
from datetime import datetime, timedelta
from django.utils import timezone

from django.conf import settings


# SNMP Models
## Device
class Device(models.Model):
	# primary key => not inherited
	macAddress = macField.MACAddressField(unique=True)
	ip = models.GenericIPAddressField(null=True)
	lastTouched = models.DateTimeField(null=True, default=lambda:(timezone.now()) )
	index = models.CharField(max_length=20, null=True) 

	def touch(self):
		self.lastTouched = timezone.now()
		self.save()

	class Meta:
		abstract = True
		ordering = ["macAddress"]


## Access Point Model
class APManage(models.Manager):
	def areUp(self):
		return super(APManage, self).filter(lastTouched__gte=(timezone.now() - 2*settings.SNMPAPLAP))

	def areDown(self):
		return super(APManage, self).filter(lastTouched__lt=(timezone.now() - 2*settings.SNMPAPLAP))

class AccessPoint(Device):
	ETHERNETLINKTYPE = ((10,'10 Mbps'),(100,'100 Mbps'),(1000,'1 Gbps'))

	name = models.CharField(max_length=50, null=True)
	location = models.CharField(max_length=50, null=True)

	ethernetLinkSpeed = models.DecimalField(max_digits=5, decimal_places=0, choices=ETHERNETLINKTYPE, null=True)


	objects = APManage()
	def __str__(self):
		return str(self.name) + " : " + str(self.macAddress) + ' (' + str(self.ip) + ')'
	
	def isUp(self):
		return lastTouched > (timezone.now() - settings.SNMPAPLAP)

	def nbrOfClients(self):
		result = 0
		for i in self.apinterface_set:
			result += i.numOfClients
		return result

## Access Point Interface Model
class APInterface(models.Model):
	TYPES = ((1,'Dot11b (2,4GHz)'),(2,'Dot11a (5GHz)'),(4,'Ultra-Wide Band'))

	index = models.CharField(max_length=3)
	ap = models.ForeignKey(AccessPoint)
	ifType = models.DecimalField(max_digits=1, decimal_places=0, choices=TYPES, null=True)

	class Meta:
		unique_together = (('ap', 'index'),)


## Rogue Access Point Model
class RAPManage(models.Manager):
	def areUp(self):
		return super(RAPManage, self).filter(lastTouched__gte=(timezone.now() - settings.SNMPRAPLAP))

class RogueAccessPoint(Device):

	ssid = models.CharField(max_length=50, default='')
	nbrOfClients = models.DecimalField(max_digits=3, decimal_places=0, default=0)
	closestAp = models.ForeignKey(AccessPoint, null= True)

	objects = RAPManage()
	def __str__(self):
		return str(self.ssid) + " : " + str(self.macAddress)
	
	def isUp(self):
		return lastTouched > (timezone.now()- settings.SNMPRAPLAP)


## Mobile stations Model
class MSManage(models.Manager):
	def areAssociated(self):
			return super(MSManage, self).filter(lastTouched__gte=(timezone.now() - settings.SNMPMSLAP))

class MobileStation(Device):
	DOT11_PROTOCOLS = (('1',"802.11a"),('2',"802.11b"),('3',"802.11g"),('6',"802.11n (2.4Ghz)"),('7',"802.11n (5Ghz)"),('4',"Unknown"),('5',"Mobile"))

	ap = models.ForeignKey(AccessPoint, related_name='associated', null=True)

	ssid = models.CharField(max_length=25, null=True, db_index=True)
	dot11protocol = models.CharField(max_length=1, choices=DOT11_PROTOCOLS, null=True, db_index=True)
	
	objects = MSManage()
	def __str__(self):
		return str(self.macAddress) + ' on ' + str(self.ssid)

	def isAssociated(self):
		return lastTouched > (timezone.now()- settings.SNMPMSLAP)


## SNMP AP Snapshot
class APSnapshot(models.Model):
	ap = models.ForeignKey(AccessPoint)
	date = models.DateTimeField(default=lambda:(timezone.now()))

class APSnapshotData(models.Model):
	apSnapshot = models.ForeignKey(APSnapshot)
	name = models.CharField(max_length=56)
	value = models.DecimalField(max_digits=10, decimal_places=0, default=0)

# SNMP AP Interface Snapshot
class APIfSnapshot(models.Model):
	apinterface = models.ForeignKey(APInterface)
	date = models.DateTimeField(default=lambda:(timezone.now()))

class APIfSnapshotData(models.Model):
	apIfSnapshot = models.ForeignKey(APIfSnapshot)
	name = models.CharField(max_length=56)
	value = models.DecimalField(max_digits=10, decimal_places=0, default=0)

######################################################################################
######################################################################################
# Log Models
## Radius Model
class RadiusEvent(models.Model):
	RADIUS_TYPES = (("ok","Login Ok"),("ko","Login Incorrect"),("er","Error"),("no","Notice"),("in","Information"))

	date = models.DateTimeField()
	microsecond = models.DecimalField(max_digits=6, decimal_places=0)

	server = models.CharField(max_length=25)
	radiusType = models.CharField(max_length=2, choices=RADIUS_TYPES) #TODO choice
	
	login = models.CharField(max_length=128, default="")
	message = models.CharField(max_length=128,default="")

	def __str__(self):
		return "" + self.radiusType + " : " +  self.login

	class Meta:
		unique_together = (('date', 'microsecond', 'login', 'message'),)

## DHCP model
class DHCPEvent(models.Model):
	DHCP_TYPES = (("log","Syslog"), ("war","Warning"), ("dis","Discover"), ("off","Offer"), ("req","Request"), ("ack","Ack"), ("nak","Nak"), ("inf", "Inform"))

	date = models.DateTimeField()
	microsecond = models.DecimalField(max_digits=6, decimal_places=0)

	server = models.CharField(max_length=10)
	device = macField.MACAddressField(null=True)
	dhcpType = models.CharField(max_length=3, choices=DHCP_TYPES)
	ip = models.GenericIPAddressField(null=True)
	message = models.CharField(max_length=256, null=True)
	via = models.GenericIPAddressField(null=True)
	class Meta:
		unique_together = (('date', 'microsecond', 'server'),)


## Wism model
class WismEvent(models.Model):
	SEVERITY_MEANING = ((0,'Emergency: System is unusable'),(1,'Alert: Action must be taken immediately'), (2,'Critical: Critical conditions'), (3,'Error: Error conditions'), (4,'Warning: Warning conditions'), (5,'Notice: Normal but significant condition'), (6,'Informational: Informational messages'), (7,'Debug: Debug-level messages'))
	date = models.DateTimeField()
	microsecond = models.DecimalField(max_digits=6, decimal_places=0)
	
	wismIp = models.GenericIPAddressField()

	category = models.CharField(max_length=10)
	severity = models.DecimalField(max_digits=1,decimal_places=0, choices=SEVERITY_MEANING)
	mnemo = models.CharField(max_length=56)

	message = models.CharField(max_length=256)

	class Meta:
		unique_together = (('date', 'microsecond', 'wismIp'),)


## Models of the probe log
class ProbeLog(models.Model):
	date = models.DateTimeField(default=lambda:(timezone.now()), unique=True)
	probe = models.ForeignKey(MobileStation)
	class Meta:
		unique_together = (('date', 'probe'),)

class ProbeTest(models.Model):
	log = models.ForeignKey(ProbeLog)

class ProbeScanResult(models.Model):
	test = models.ForeignKey(ProbeTest)
	ap = models.ForeignKey(AccessPoint)
	ssid = models.CharField(max_length=50)
	frequency = models.DecimalField(max_digits=4,decimal_places=0)
	signalStrength = models.DecimalField(max_digits=3,decimal_places=0)

class ProbeConnectionResult(models.Model):
	date = models.DateTimeField()
	ssid = models.CharField(max_length=50)
	test = models.ForeignKey(ProbeTest)
	apTried = models.ManyToManyField(AccessPoint, related_name='tried+')
	connected = models.ManyToManyField(AccessPoint,related_name='connected+')


class TimeCheck(models.Model):
	result = models.ForeignKey(ProbeConnectionResult)
	step = models.CharField(max_length=50)
	time = models.DecimalField(max_digits=5,decimal_places=0)

class ServiceCheck(models.Model):
	result = models.ForeignKey(ProbeConnectionResult)
	service = models.CharField(max_length=50)
	state = models.BooleanField()



## Error Parsing
class BadLog(models.Model):
	log = models.CharField(max_length=1024)
	cause = models.CharField(max_length=256)
	def __str__(self):
		return "" + self.log + " --> " +  self.cause + '\n'



################## Auxiliary Models #######################
## Tasks model
class CurrentTask(models.Model):
	lastTouched = models.DateTimeField(default=lambda:(timezone.now()))
	name = models.CharField(max_length=25, primary_key=True)
 	
	def touch(self):
		self.lastTouched = timezone.now()
		self.save()

	def __str__(self):
		return self.name

## Operational Errors Model
class OperationalError(models.Model):
	date = models.DateTimeField(default=lambda:(timezone.now()))
	source = models.CharField(max_length=100)
	error = models.CharField(max_length=250)

	def __str__(self):
		return str(self.date) + ": " + self.error + " (from " + self.source + ")"

####################

netwObserver/analyse/views.py
from django.shortcuts import render
from analyse.computation import aggregator
from analyse.observation import monitoring
from gatherer.models import *
from django.core.exceptions import ObjectDoesNotExist

from datetime import datetime

# Create your views here.
def general(request):
	context = {}
	context['app'] = 'analysis'
	context['cat'] = 'gen'
	
	context['wronglyPlugged'] = len(monitoring.getDhcpWrongPlugAlerts())
	context['nbrUsers'] = aggregator.getNbrOfUsers()
	context['nbrAP'] = aggregator.getNbrOfAP()

	return render(request, "analyse/general.html", context)

def controller(request):
	context = {}
	context["cat"] = 'controller'
	context['app'] = 'analysis'

	context['byCategory'] = aggregator.getWismLogsByCategory()

	return render(request, "analyse/controller.html", context)


def wifiOverview(request):
	context= {}
	context['app'] = 'analysis'
	context['cat'] = 'wifi'
	context['section'] = 'overview'

	context["hotAP"] = monitoring.getOverloadedAP()[:10]
	context["apDown"] = AccessPoint.objects.areDown()

	return render(request, "analyse/wifiOverview.html", context)

def wifiAP(request, order='name'):
	context= {}
	context['app'] = 'analysis'
	context['cat'] = 'wifi'
	context['section'] = 'ap'

	context["allAP"] = AccessPoint.objects.all().order_by('name')

	if request.method == 'GET' and 'selectedAP' in request.GET:
		try:
			context["ap"] = AccessPoint.objects.get(id=int(request.GET['selectedAP']))
			context["apData"] = aggregator.getAPData(context["ap"])
			context["interfaceData"] = aggregator.getAllIfData(context["ap"])
		except:
			pass

	return render(request, "analyse/wifiAP.html", context)

def wifiRAP(request):
	context= {}
	context['app'] = 'analysis'
	context['cat'] = 'wifi'
	context['section'] = 'rap'

	context['perZone'] = aggregator.getRapPerZone()

	return render(request, "analyse/wifiRAP.html", context)

def wifiUsers(request):
	context= {}
	context['app'] = 'analysis'
	context['cat'] = 'wifi'
	context['section'] = 'users'

	context["proto"] = aggregator.getUsersByDot11Protocol()
	context["ssid"] = aggregator.getUsersBySSID()

	return render(request, "analyse/wifiUsers.html", context)

def wifiProbes(request):
	context= {}
	context['app'] = 'analysis'
	context['cat'] = 'wifi'
	context['section'] = 'probes'
	
	context["allProbe"] = aggregator.getAllProbes()
	context["connectionService"] = aggregator.getAvailabilityByService()

	if request.method == 'GET' and 'selectedProbe' in request.GET:
		try:
			context["probe"] = MobileStation.objects.get(id=int(request.GET['selectedProbe']))
			context["lastScan"] = aggregator.getLastScan(context["probe"])
			context["connectionTime"] = aggregator.getConnectionTime(context["probe"])
		except:
			pass

	return render(request, "analyse/wifiProbe.html", context)

def dhcpAlerts(request):
	context= {}
	context['app'] = 'analysis'
	context['cat'] = 'dhcp'
	context['section'] = 'alerts'

	context['active'] = monitoring.isDhcpActive()
	context['leaseAlerts'] = monitoring.getDhcpLeaseAlerts()
	context['wronglyPlugged'] = monitoring.getDhcpWrongPlugAlerts()

	return render(request, "analyse/dhcpAlerts.html", context)

def dhcpGraph(request):
	context= {}
	context['app'] = 'analysis'
	context['cat'] = 'dhcp'
	context['section'] = 'graph'
	
	context['byType'] = aggregator.getDhcpLogByType()

	return render(request, "analyse/dhcpGraph.html", context)


def radius(request):
	context= {}
	context['app'] = 'analysis'
	context['cat'] = 'radius'

	context['successRate'] = aggregator.getRadiusSuccessRate()

	return render(request, "analyse/radius.html", context)

netwObserver/analyse/templates/analyse/analyse.html
{% extends "common/base.html" %}
{% load staticfiles %}

{% block customHeader %}
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
{% endblock %}

{% block content %}
<div class='row' style="margin-top:20px;">
	<div class="col-md-2">
		<ul class="nav nav-pills nav-stacked">
			<li {% if cat == 'gen' %}class="active"{%endif%}><a href="{% url 'general' %}">General</a></li>
			<li {% if cat == 'wifi' %}class="active"{%endif%}><a href="{% url 'wifi' %}">Wifi</a></li>
			<li {% if cat == 'controller' %}class="active"{%endif%}><a href="{% url 'controller'%}">Controller</a></li>
			<li {% if cat == 'dhcp' %}class="active"{%endif%}><a href="{% url 'dhcp'%}">DHCP</a></li>
			<li {% if cat == 'radius' %}class="active"{%endif%}><a href="{% url 'radius'%}">Radius</a></li>
		</ul>
	</div>

	<div id="categorie" class="col-md-10">
	{% block category %}

	{%endblock%}
	</div>
</div>

{% endblock %}

netwObserver/analyse/templates/analyse/controller.html
{% extends "analyse/analyse.html" %}
{% load staticfiles %}

{%block category%}

<script type="text/javascript">
	// Load the Visualization API and the piechart package.
	google.load('visualization', '1.0', {'packages':['corechart']});

	// Set a callback to run when the Google Visualization API is loaded.
	google.setOnLoadCallback(drawCategoryLogs);

	function drawCategoryLogs() {

		var data = new google.visualization.DataTable();
		data.addColumn('string', 'Category');
		data.addColumn('number', 'Quantity of logs');
		data.addRows([
			{%for cat, qty in byCategory.items%}
			['{{cat}}', {{qty}}],
			{%endfor%}
			]);
		data.sort([{column: 0}]);
		var options = {'title':'Wism Logs by Category',
			'width':900,
			'height':500};

		var chart = new google.visualization.PieChart(document.getElementById('categorylogs_div'));

		chart.draw(data, options);
	}
</script>
<div id="categorylogs_div" style="width:400; height:300"></div>

{%endblock%}

netwObserver/analyse/templates/analyse/dhcp.html
{% extends "analyse/analyse.html" %}
{% load staticfiles %}

{%block category%}

<div class="container">
<ul class="nav nav-tabs">
  <li {% if section == 'alerts' %}class="active"{%endif%}><a href="{% url 'dhcpalerts' %}">Overview</a></li>
  <li {% if section == 'graph' %}class="active"{%endif%}><a href="{% url 'dhcpgraph' %}">Graph</a></li>
</ul>
</div>
{% block section %}

{%endblock%}
{%endblock%}

netwObserver/analyse/templates/analyse/dhcpAlerts.html
{% extends "analyse/dhcp.html" %}
{% load staticfiles %}

{% block section %}
<div class="container">

	{%if active == True%}
	<div class="alert alert-success">DHCP is up and running</div>
	{%else%}
	<div class="alert alert-warning">No DHCP activity detected</div>
	{%endif%}

	{%if leaseAlerts%}
	<div class="panel panel-info">
		<div class="panel-heading">Scattering of the lease alerts</div>
		<div class="panel-body">
			<dl class="dl-horizontal">
				<dt>Number of alerts</dt>
				<dd>{{leaseAlerts.alerts}}</dd>
				<dt>Affected devices</dt>
				<dd>{{leaseAlerts.devices}}</dd>
				<dt>Scatter-degree</dt>
				<dd>{{leaseAlerts.ratio|floatformat:-2}}</dd>
			</dl>
		</div>
	</div>
	{%endif%}

	{%if wronglyPlugged%}
	<div class="panel panel-warning">
		<div class="panel-heading">The following devices may be connected on a wrong plug</div>
		<div class="panel-body">
		{%for dev, infos in wronglyPlugged.items %}
		<h5>{{dev}}</h5>
		<dl class="dl-horizontal">
			<dt>Plugged on</dt>
			<dd>{{infos.via}}</dd>
			<dt>Last seen</dt>
			<dd>{{infos.date}}</dd>
		</dl>
		{%endfor%}
		</div>
	</div>
	{%endif%}

</div>
{%endblock%}

netwObserver/analyse/templates/analyse/dhcpGraph.html
{% extends "analyse/dhcp.html" %}
{% load staticfiles %}

{% block section %}
{% if byType %}
<script type="text/javascript">
	
	google.load("visualization", "1", {packages:["corechart"]});
	
	google.setOnLoadCallback(dhcpChart);
	
	function dhcpChart() {
		
		var data = google.visualization.arrayToDataTable([
			['Types', 'Quantity'],
			{%for t,qty in byType%}
			["{{t}}", {{qty}}],
			{%endfor%}
		]);

		var options = {
			title: 'DHCP Packet by Types',
		};

		var chart = new google.visualization.BarChart(document.getElementById('dhcpchart_div'));
		
		chart.draw(data, options);
	}
</script>

<div id="dhcpchart_div" style="width: 900px; height: 500px;"></div>
{%endif%}
{%endblock%}

netwObserver/analyse/templates/analyse/wifiAP.html
{% extends "analyse/wifi.html" %}
{% load staticfiles %}
{% load tz %}

{% localtime on %}
{% block section %}
<div class="container" style='margin-top: 25px;'>
<form method="get"  action="{% url 'wifiAP' %}" class="form-horizontal" role="form">
	<div class="form-group">
		<label for="selectedAP" class="col-md-2 control-label">Access Point</label>
		<div class="col-md-6">			
			<select class="form-control" name="selectedAP" id="selectedAP">
				<option value="" selected></option>
				{% if allAP %}
				{% for ap in allAP %}
				<option value="{{ap.id}}">{{ap.name}}</option>
				{% endfor %}
				{% endif %}
			</select>
		</div>
		<button type="submit" class="btn btn-default">
			<span class="glyphicon glyphicon-signal"></span> Get
		</button>
	</div>
</form>
</div>
{%if apData%}
<script type="text/javascript">
	google.load('visualization', '1.0', {'packages':['corechart']});
	google.setOnLoadCallback(drawBandwidthChart);

	function drawBandwidthChart() {
		
		var data = google.visualization.arrayToDataTable([
		  ['Time', 'Rx Speed', 'Tx Speed'],
		  {%for log in apData%}
		  [new Date({{log.date.year}},{{log.date.month}}-1,{{log.date.day}},{{log.date.hour}},{{log.date.minute}},{{log.date.second}}), {{log.data.ethernetRxTotalBytes}}, {{log.data.ethernetTxTotalBytes}}],
		  {%endfor%}
		]);

		var options = {
		  title: 'Access Point Bandwidth (Mb/s)',
		  curveType : 'function',
		};

		var chart = new google.visualization.LineChart(document.getElementById('bandwidthchart_div'));
		chart.draw(data, options);
	}

	{%for i in interfaceData%}
	google.setOnLoadCallback(drawInterface{{forloop.counter0}}Chart);
	function drawInterface{{forloop.counter0}}Chart() {
		
		var data = google.visualization.arrayToDataTable([
		  ['Time', 'Clients', 'Clients with Poor SNR', 'Channel Utilization'],
		  {%for log in i.data%}
		  [new Date({{log.date.year}},{{log.date.month}}-1,{{log.date.day}},{{log.date.hour}},{{log.date.minute}},{{log.date.second}}), {{log.data.numOfClients}}, {{log.data.numOfPoorSNRClients}} , {{log.data.channelUtilization}}/100],
		  {%endfor%}
		]);

		var options = {
			series: {2:{targetAxisIndex:1, format:'#,##%', curveType:'function'}},
			vAxes:[
				{}, 
				{title:'Channel Utilization',format: '#%'}
			],
			title: 'Occupancy',
		};

		var chart = new google.visualization.LineChart(document.getElementById('interface{{forloop.counter0}}chart_div'));
		chart.draw(data, options);
	}

	{%endfor%}

</script>

<h3>{{ap.name}}</h3>
<dl class="dl-horizontal">
	<dt>IP Address</dt>
	<dd>{{ap.ip}}</dd>	
	<dt>Mac Address</dt>
	<dd>{{ap.macAddress}}</dd>
	<dt>Ethernet Link</dt>
	<dd>{{ap.ethernetLinkSpeed}} Mb/s</dd>
</dl>
<div id="bandwidthchart_div" style="width: 900px; height: 500px;"></div>



{%for i in interfaceData%}
<h4>Interface {{i.interface.get_ifType_display}}</h4>
<div id="interface{{forloop.counter0}}chart_div" style="width: 900px; height: 500px;"></div>
{%endfor%}


{%endif%}
{%endblock%}
{% endlocaltime %}

netwObserver/analyse/templates/analyse/wifiProbe.html
{% extends "analyse/wifi.html" %}
{% load staticfiles %}


{% block section %}
<div class="container" style='margin-top: 25px;'>

{%if connectionService%}
<h4>Services Availability</h4>
<table class="table table-bordered">
	<thead>
		<tr>
			<th></th>
			{%for ssid in connectionService.ssids%}
			<th>{{ssid}}</th>
			{%endfor%}
		</tr>
	</thead>
	<tbody>
		{%for service in connectionService.data%}
		<tr>
			<td>{{service.service}}</td>
			{%for rate in service.data%}
			<td {%if rate < 50 %}class="danger"{%else%}class="success"{%endif%}>{{rate|floatformat:-2}}</td>
			{%endfor%}
		</tr>
		{%endfor%}
	</tbody>
</table>
{%endif%}
<form method="get"  action="{% url 'wifiProbes' %}" class="form-horizontal" role="form">
	<label for="selectedProbe" class="col-md-2 control-label">Probes</label>
	<div class="col-md-6">			
		<select class="form-control" name="selectedProbe" id="selectedProbe">
			<option value="" selected></option>
			{% if allProbe %}
			{% for p in allProbe %}
			<option value="{{p.id}}">{{p.macAddress}}</option>
			{% endfor %}
			{% endif %}
		</select>
	</div>
	<button type="submit" class="btn btn-default">
		<span class="glyphicon glyphicon-signal"></span> Get
	</button>
</form>
</div>

{%if probe%}
<div class="container" style='margin-top: 25px;'>
<h3>Probe</h3>
<dl class="dl-horizontal">
	<dt>Mac Address</dt>
	<dd>{{probe.macAddress}}</dd>
	<dt>802.11 Protocol</dt>
	<dd>{{probe.get_dot11protocol_display}}</dd>
</dl>
{%if lastScan%}
<h3>Last Scan Results <small>{{lastScan.date}}</small></h3>
<table class="table table-striped table-hover">
	<thead>
		<tr>
			<th>Access Point Name</th>
			<th>Mac Address</th>
			<th>Link</th>
			<th>Average Signal Strength</th>
			<th>Detected SSID</th>
			<th>Frequencies</th>
		</tr>
	</thead>
 	<tbody>
		{% for mac,ap in lastScan.results.items %}
		<tr>
			<td>{{ap.ap.name}}</td>
			<td>{{mac}}</td>
			<td>{{ap.ap.get_ethernetLinkSpeed_display}}</td>
			<td>{{ ap.signalStrength|floatformat:-2 }} dBm</td>
			<td>
				<ul class="list-unstyled">
					{%for ssid in ap.ssid%}
					<li>{{ssid}}</li>
					{%endfor%}
				</ul>
			</td>
			<td>
				<ul class="list-unstyled">
					{%for freq in ap.frequency%}
					<li>{{freq}} hz</li>
					{%endfor%}
				</ul>
			</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
</div>
{%endif%}

{%if connectionTime%}
<script type="text/javascript">
	google.load('visualization', '1.0', {'packages':['corechart']});
	

	{%for ssid, result in connectionTime.items%}
	google.setOnLoadCallback(draw{{ssid}}ConnectionTimeChart);
	function draw{{ssid}}ConnectionTimeChart() {
		
		var data = google.visualization.arrayToDataTable([

		  ['Time'{%for check in result.0.times%} ,'{{check.step}}'{%endfor%}],
		  {%for connection in result%}
		  [new Date({{connection.date.year}},{{connection.date.month}}-1,{{connection.date.day}},{{connection.date.hour}},{{connection.date.minute}},{{connection.date.second}}){%for check in connection.times%} ,{{check.time}}{%endfor%}],
		  {%endfor%}
		]);

		var options = {
			title: 'Connection time (seconds)',
		};

		var chart = new google.visualization.LineChart(document.getElementById('{{ssid}}timeschart_div'));
		chart.draw(data, options);
	}
	google.setOnLoadCallback(draw{{ssid}}ConnectionAttemptChart);
	function draw{{ssid}}ConnectionAttemptChart() {
		
		var data = google.visualization.arrayToDataTable([

		  ['Connection', "Association attempts","Reconnections"],
		  {%for connection in result%}
		  [new Date({{connection.date.year}},{{connection.date.month}}-1,{{connection.date.day}},{{connection.date.hour}},{{connection.date.minute}},{{connection.date.second}}), {{connection.connection.apTried.count}}, {{connection.connection.connected.count}}-1],
		  {%endfor%}
		]);

		var options = {
			title: 'Number of Association Attempts and Connections',
		};

		var chart = new google.visualization.LineChart(document.getElementById('{{ssid}}attemptchart_div'));
		chart.draw(data, options);
	}
	{%endfor%}
</script>
{%endif%}
{%for ssid, result in connectionTime.items%}
<h4>SSID: {{result.0.connection.ssid}}</h4>
<div id="{{ssid}}timeschart_div" style="width: 900px; height: 500px;"></div>
<div id="{{ssid}}attemptchart_div" style="width: 900px; height: 500px;"></div>
{%endfor%}
{%endif%}

{%endblock%}