netwObserver/analyse/urls.py
from django.conf.urls import patterns, url

from analyse import views

urlpatterns = patterns('',
	url(r'^$', views.general),
	url(r'general/', views.general, name='general'),
	
	url(r'wifi/ap', views.wifiAP, name='wifiAP'),
	url(r'wifi/rap', views.wifiRAP, name='wifiRAP'),
	url(r'wifi/users', views.wifiUsers, name='wifiUsers'),
	url(r'wifi/probes', views.wifiProbes, name='wifiProbes'),
	url(r'wifi/', views.wifiOverview, name='wifi'),

	url(r'controller/', views.controller, name='controller'),
	
	url(r'dhcp/alerts', views.dhcpAlerts, name='dhcpalerts'),
	url(r'dhcp/graph', views.dhcpGraph, name='dhcpgraph'),
	url(r'dhcp/', views.dhcpAlerts, name='dhcp'),
	

	url(r'radius/', views.radius, name='radius'),
)

netwObserver/gatherer/urls.py
from django.conf.urls import patterns, url

from gatherer import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^logs/$', views.dhcplogs, name='logs'),

	url(r'^logs/wism/(?P<page>\d+)', views.wismlogs, name='wismlogs'),
	url(r'^logs/wism/', views.wismlogs, name='wismlogs'),

	url(r'^logs/dhcp/(?P<page>\d+)', views.dhcplogs, name='dhcplogs'),
	url(r'^logs/dhcp/', views.dhcplogs, name='dhcplogs'),
	
	url(r'^logs/radius/(?P<page>\d+)', views.radiuslogs, name='radiuslogs'),
	url(r'^logs/radius/', views.radiuslogs, name='radiuslogs'),
	
	url(r'^snmp/$', views.apsnmp, name='snmp'),

	url(r'^snmp/ap/refresh', views.apsnmpRefresh, name='aprefresh'),
	url(r'^snmp/ap/(?P<page>\d+)', views.apsnmp, name='apsnmp'),
	url(r'^snmp/ap', views.apsnmp, name='apsnmp'),

	url(r'^snmp/ms/refresh', views.mssnmpRefresh, name='msrefresh'),
	url(r'^snmp/ms/(?P<page>\d+)', views.mssnmp, name='mssnmp'),
	url(r'^snmp/ms', views.mssnmp, name='mssnmp'),

	url(r'^snmp/rap/refresh', views.rapsnmpRefresh, name='raprefresh'),
	url(r'^snmp/rap/(?P<page>\d+)', views.rapsnmp, name='rapsnmp'),
	url(r'^snmp/rap', views.rapsnmp, name='rapsnmp'),

)

netwObserver/netwObserver/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
	# Examples:
    url(r'^$', 'netwObserver.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^gatherer/', include('gatherer.urls')),
    url(r'^analysis/', include('analyse.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

netwObserver/gatherer/models.py
from django.db import models
from custom import macField
from datetime import datetime, timedelta
from django.utils import timezone

from django.conf import settings


# SNMP Models
## Device
class Device(models.Model):
	# primary key => not inherited
	macAddress = macField.MACAddressField(unique=True)
	ip = models.GenericIPAddressField(null=True)
	lastTouched = models.DateTimeField(null=True, default=lambda:(timezone.now()) )
	index = models.CharField(max_length=20, null=True) 

	def touch(self):
		self.lastTouched = timezone.now()
		self.save()

	class Meta:
		abstract = True
		ordering = ["macAddress"]


## Access Point Model
class APManage(models.Manager):
	def areUp(self):
		return super(APManage, self).filter(lastTouched__gte=(timezone.now() - 2*settings.SNMPAPLAP))

	def areDown(self):
		return super(APManage, self).filter(lastTouched__lt=(timezone.now() - 2*settings.SNMPAPLAP))

class AccessPoint(Device):
	ETHERNETLINKTYPE = ((10,'10 Mbps'),(100,'100 Mbps'),(1000,'1 Gbps'))

	name = models.CharField(max_length=50, null=True)
	location = models.CharField(max_length=50, null=True)

	ethernetLinkSpeed = models.DecimalField(max_digits=5, decimal_places=0, choices=ETHERNETLINKTYPE, null=True)


	objects = APManage()
	def __str__(self):
		return str(self.name) + " : " + str(self.macAddress) + ' (' + str(self.ip) + ')'
	
	def isUp(self):
		return lastTouched > (timezone.now() - settings.SNMPAPLAP)

	def nbrOfClients(self):
		result = 0
		for i in self.apinterface_set:
			result += i.numOfClients
		return result

## Access Point Interface Model
class APInterface(models.Model):
	TYPES = ((1,'Dot11b (2,4GHz)'),(2,'Dot11a (5GHz)'),(4,'Ultra-Wide Band'))

	index = models.CharField(max_length=3)
	ap = models.ForeignKey(AccessPoint)
	ifType = models.DecimalField(max_digits=1, decimal_places=0, choices=TYPES, null=True)

	class Meta:
		unique_together = (('ap', 'index'),)


## Rogue Access Point Model
class RAPManage(models.Manager):
	def areUp(self):
		return super(RAPManage, self).filter(lastTouched__gte=(timezone.now() - settings.SNMPRAPLAP))

class RogueAccessPoint(Device):

	ssid = models.CharField(max_length=50, default='')
	nbrOfClients = models.DecimalField(max_digits=3, decimal_places=0, default=0)
	closestAp = models.ForeignKey(AccessPoint, null= True)

	objects = RAPManage()
	def __str__(self):
		return str(self.ssid) + " : " + str(self.macAddress)
	
	def isUp(self):
		return lastTouched > (timezone.now()- settings.SNMPRAPLAP)


## Mobile stations Model
class MSManage(models.Manager):
	def areAssociated(self):
			return super(MSManage, self).filter(lastTouched__gte=(timezone.now() - settings.SNMPMSLAP))

class MobileStation(Device):
	DOT11_PROTOCOLS = (('1',"802.11a"),('2',"802.11b"),('3',"802.11g"),('6',"802.11n (2.4Ghz)"),('7',"802.11n (5Ghz)"),('4',"Unknown"),('5',"Mobile"))

	ap = models.ForeignKey(AccessPoint, related_name='associated', null=True)

	ssid = models.CharField(max_length=25, null=True, db_index=True)
	dot11protocol = models.CharField(max_length=1, choices=DOT11_PROTOCOLS, null=True, db_index=True)
	
	objects = MSManage()
	def __str__(self):
		return str(self.macAddress) + ' on ' + str(self.ssid)

	def isAssociated(self):
		return lastTouched > (timezone.now()- settings.SNMPMSLAP)


## SNMP AP Snapshot
class APSnapshot(models.Model):
	ap = models.ForeignKey(AccessPoint)
	date = models.DateTimeField(default=lambda:(timezone.now()))

class APSnapshotData(models.Model):
	apSnapshot = models.ForeignKey(APSnapshot)
	name = models.CharField(max_length=56)
	value = models.DecimalField(max_digits=10, decimal_places=0, default=0)

# SNMP AP Interface Snapshot
class APIfSnapshot(models.Model):
	apinterface = models.ForeignKey(APInterface)
	date = models.DateTimeField(default=lambda:(timezone.now()))

class APIfSnapshotData(models.Model):
	apIfSnapshot = models.ForeignKey(APIfSnapshot)
	name = models.CharField(max_length=56)
	value = models.DecimalField(max_digits=10, decimal_places=0, default=0)

######################################################################################
######################################################################################
# Log Models
## Radius Model
class RadiusEvent(models.Model):
	RADIUS_TYPES = (("ok","Login Ok"),("ko","Login Incorrect"),("er","Error"),("no","Notice"),("in","Information"))

	date = models.DateTimeField()
	microsecond = models.DecimalField(max_digits=6, decimal_places=0)

	server = models.CharField(max_length=25)
	radiusType = models.CharField(max_length=2, choices=RADIUS_TYPES) #TODO choice
	
	login = models.CharField(max_length=128, default="")
	message = models.CharField(max_length=128,default="")

	def __str__(self):
		return "" + self.radiusType + " : " +  self.login

	class Meta:
		unique_together = (('date', 'microsecond', 'login', 'message'),)

## DHCP model
class DHCPEvent(models.Model):
	DHCP_TYPES = (("log","Syslog"), ("war","Warning"), ("dis","Discover"), ("off","Offer"), ("req","Request"), ("ack","Ack"), ("nak","Nak"), ("inf", "Inform"))

	date = models.DateTimeField()
	microsecond = models.DecimalField(max_digits=6, decimal_places=0)

	server = models.CharField(max_length=10)
	device = macField.MACAddressField(null=True)
	dhcpType = models.CharField(max_length=3, choices=DHCP_TYPES)
	ip = models.GenericIPAddressField(null=True)
	message = models.CharField(max_length=256, null=True)
	via = models.GenericIPAddressField(null=True)
	class Meta:
		unique_together = (('date', 'microsecond', 'server'),)


## Wism model
class WismEvent(models.Model):
	SEVERITY_MEANING = ((0,'Emergency: System is unusable'),(1,'Alert: Action must be taken immediately'), (2,'Critical: Critical conditions'), (3,'Error: Error conditions'), (4,'Warning: Warning conditions'), (5,'Notice: Normal but significant condition'), (6,'Informational: Informational messages'), (7,'Debug: Debug-level messages'))
	date = models.DateTimeField()
	microsecond = models.DecimalField(max_digits=6, decimal_places=0)
	
	wismIp = models.GenericIPAddressField()

	category = models.CharField(max_length=10)
	severity = models.DecimalField(max_digits=1,decimal_places=0, choices=SEVERITY_MEANING)
	mnemo = models.CharField(max_length=56)

	message = models.CharField(max_length=256)

	class Meta:
		unique_together = (('date', 'microsecond', 'wismIp'),)


## Models of the probe log
class ProbeLog(models.Model):
	date = models.DateTimeField(default=lambda:(timezone.now()), unique=True)
	probe = models.ForeignKey(MobileStation)
	class Meta:
		unique_together = (('date', 'probe'),)

class ProbeTest(models.Model):
	log = models.ForeignKey(ProbeLog)

class ProbeScanResult(models.Model):
	test = models.ForeignKey(ProbeTest)
	ap = models.ForeignKey(AccessPoint)
	ssid = models.CharField(max_length=50)
	frequency = models.DecimalField(max_digits=4,decimal_places=0)
	signalStrength = models.DecimalField(max_digits=3,decimal_places=0)

class ProbeConnectionResult(models.Model):
	date = models.DateTimeField()
	ssid = models.CharField(max_length=50)
	test = models.ForeignKey(ProbeTest)
	apTried = models.ManyToManyField(AccessPoint, related_name='tried+')
	connected = models.ManyToManyField(AccessPoint,related_name='connected+')


class TimeCheck(models.Model):
	result = models.ForeignKey(ProbeConnectionResult)
	step = models.CharField(max_length=50)
	time = models.DecimalField(max_digits=5,decimal_places=0)

class ServiceCheck(models.Model):
	result = models.ForeignKey(ProbeConnectionResult)
	service = models.CharField(max_length=50)
	state = models.BooleanField()



## Error Parsing
class BadLog(models.Model):
	log = models.CharField(max_length=1024)
	cause = models.CharField(max_length=256)
	def __str__(self):
		return "" + self.log + " --> " +  self.cause + '\n'



################## Auxiliary Models #######################
## Tasks model
class CurrentTask(models.Model):
	lastTouched = models.DateTimeField(default=lambda:(timezone.now()))
	name = models.CharField(max_length=25, primary_key=True)
 	
	def touch(self):
		self.lastTouched = timezone.now()
		self.save()

	def __str__(self):
		return self.name

## Operational Errors Model
class OperationalError(models.Model):
	date = models.DateTimeField(default=lambda:(timezone.now()))
	source = models.CharField(max_length=100)
	error = models.CharField(max_length=250)

	def __str__(self):
		return str(self.date) + ": " + self.error + " (from " + self.source + ")"

####################

netwObserver/gatherer/views.py
from os import listdir
from os.path import isfile,join, splitext
from threading import Thread
from datetime import timedelta

from django.core.context_processors import csrf
from django.db import IntegrityError
from django.shortcuts import render
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from gatherer.log.logParser import parser
from gatherer.snmp.getter import getAllAP
from gatherer.models import RadiusEvent, DHCPEvent, WismEvent, MobileStation, AccessPoint, RogueAccessPoint, BadLog
from gatherer.tasks import snmpRAPDaemon, snmpMSDaemon, snmpAPDaemon

from django.conf import settings

TMPFILE=settings.MEDIA_ROOT
SEVERITYMEANING = ['Emergency: System is unusable','Alert: Action must be taken immediately', 'Critical: Critical conditions', 'Error: Error conditions', 'Warning: Warning conditions', 'Notice: Normal but significant condition', 'Informational: Informational messages', 'Debug: Debug-level messages']

def index(request):
	context = {}
	context['app'] = 'gatherer'
	context['logFiles'] = [ f for f in listdir(TMPFILE) if isfile(join(TMPFILE,f)) and not f.startswith(".") and not f.endswith('.badLogs')]
	context.update(csrf(request))

	if request.method == 'POST':
		if 'selectLogFile' in request.POST:
			if request.POST.get('selectLogFile','') in context["logFiles"]:
				Thread(target=parser, args=(join(TMPFILE,request.POST.get('selectLogFile','')),) ).start()
				#parser(join(TMPFILE,request.POST.get('selectLogFile','')))

	return render(request, "gatherer/index.html", context)

def wismlogs(request, page=1, perpage=100, filters={}):
	context = {}
	context['app'] = 'gatherer'
	context['cat'] = 'wism'

	context['sevMeaning'] = SEVERITYMEANING
	tmpQuery = WismEvent.objects.order_by('-date','-microsecond')
	
	p = Paginator(tmpQuery,perpage)
	try:
		context['wismEvent'] = p.page(page)
	except PageNotAnInteger:
		context['wismEvent'] = p.page(1)
	except EmptyPage:
		context['wismEvent'] = p.page(p.num_pages)

	return render(request, "gatherer/wismlogs.html", context)



def radiuslogs(request, page=1, perpage=100, filters={}):
	context = {}
	context['app'] = 'gatherer'
	context['cat'] = 'radius'

	tmpQuery = RadiusEvent.objects.order_by('-date','-microsecond')
	p = Paginator(tmpQuery,perpage)
	try:
		context['radiusEvent'] = p.page(page)
	except PageNotAnInteger:
		context['radiusEvent'] = p.page(1)
	except EmptyPage:
		context['radiusEvent'] = p.page(p.num_pages)

	return render(request, "gatherer/radiuslogs.html", context)

def dhcplogs(request, page=1, perpage=100, filters={}):
	context = {}
	context['app'] = 'gatherer'
	context['cat'] = 'dhcp'

	tmpQuery = DHCPEvent.objects.order_by('-date','-microsecond')
		
	if "filterDate" in filters:
		tmpQuery = tmpQuery.filter(date__gte=filters['filterDate'][0])
		tmpQuery = tmpQuery.filter(date__gte=filters['filterDate'][1])
	if 'filterIP' in filters:
		tmpQuery = tmpQuery.filter(ip__exact=filters['filterIP'])
	if 'filterType' in filters:
		tmpQuery = tmpQuery.filter(dhcpType__exact=filters['filterType'])
	if 'filterDevice' in filters:
		tmpQuery = tmpQuery.filter(device_macAddress=filters['filterDevice'])
	
	p = Paginator(tmpQuery,perpage)
	try:
		context['dhcpEvent'] = p.page(page)
	except PageNotAnInteger:
		context['dhcpEvent'] = p.page(1)
	except EmptyPage:
		context['dhcpEvent'] = p.page(p.num_pages)


	return render(request, "gatherer/dhcplogs.html", context)

def apsnmpRefresh(request):
	snmpAPDaemon.delay()
	return apsnmp(request)

def apsnmp(request, page=1, perpage=100):
	AUTHORIZED_ORDER = ["name", "-name", "macAddress", "-macAddress", "ip", "-ip", "ethernetLinkSpeed", "-ethernetLinkSpeed"]

	context = {}
	context['app'] = 'gatherer'
	context['cat'] = 'ap'

	tmpQuery = AccessPoint.objects.areUp()
	if "order" in request.GET and request.GET["order"] in AUTHORIZED_ORDER:
		context["order"] = request.GET["order"]
		tmpQuery = tmpQuery.order_by(request.GET["order"])
	else:
		tmpQuery = tmpQuery.order_by('name')
		context["order"] = "name"

	p = Paginator(tmpQuery,perpage)
	try:
		context['ap'] = p.page(page)
	except PageNotAnInteger:
		context['ap'] = p.page(1)
	except EmptyPage:
		context['ap'] = p.page(p.num_pages)

	return render(request, "gatherer/apsnmp.html", context)

def mssnmpRefresh(request):
	snmpMSDaemon.delay()
	return mssnmp(request)

def mssnmp(request, page=1, perpage=100):
	context = {}
	context['app'] = 'gatherer'
	context['cat'] = 'ms'

	tmpQuery = MobileStation.objects.areAssociated().order_by('macAddress')
	p = Paginator(tmpQuery,perpage)
	try:
		context['ms'] = p.page(page)
	except PageNotAnInteger:
		context['ms'] = p.page(1)
	except EmptyPage:
		context['ms'] = p.page(p.num_pages)

	return render(request, "gatherer/mssnmp.html", context)

def rapsnmpRefresh(request):
	snmpRAPDaemon.delay()
	return rapsnmp(request)

def rapsnmp(request, page=1, perpage=100):
	context = {}
	context['app'] = 'gatherer'
	context['cat'] = 'rap'

	tmpQuery = RogueAccessPoint.objects.order_by('-nbrOfClients','ssid')
	p = Paginator(tmpQuery,perpage)
	try:
		context['rap'] = p.page(page)
	except PageNotAnInteger:
		context['rap'] = p.page(1)
	except EmptyPage:
		context['rap'] = p.page(p.num_pages)

	return render(request, "gatherer/rapsnmp.html", context)

netwObserver/gatherer/templates/gatherer/apsnmp.html
{% extends "gatherer/snmp.html" %}
{% load staticfiles %}

{%block category%}
<table class="table table-striped table-hover">
	<thead>
		<tr>
			<th><a href="{% url 'aprefresh' %}"><span class="glyphicon glyphicon-refresh"></span></a></th>
			<th>
  				Name <a href="{% url 'apsnmp' %}?order=name"><span class="glyphicon glyphicon-sort"></span></a>
			</th>
			<th>
				Mac Address <a href="{% url 'apsnmp' %}?order=macAddress"><span class="glyphicon glyphicon-sort"></span></a>
			</th>
			<th>
				IP <a href="{% url 'apsnmp' %}?order=ip"><span class="glyphicon glyphicon-sort"></span></a>
			</th>
			<th>
				Link <a href="{% url 'apsnmp' %}?order=ethernetLinkSpeed"><span class="glyphicon glyphicon-sort"></span></a>
			</th>
		</tr>
	</thead>
 	<tbody>
		{% for point in ap %}
		<tr>
			<td>
				<a href="{% url 'wifiAP' %}?selectedAP={{point.id}}"><span class="glyphicon glyphicon-signal"></span></a>
			</td>
			<td>{{point.name}}</td>
			<td>{{point.macAddress}}</td>
			<td>{{point.ip}}</td>
			<td>{{point.get_ethernetLinkSpeed_display}}</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
<footer>
	{{ap|length}} entr{{ ap|pluralize:'y,ies' }}
	{%if ap.paginator.num_pages > 1 %}
	<p class="text-center">Page {{ ap.number }} of {{ ap.paginator.num_pages }}</p>
	<ul class="pager">
		<li class="previous{%if not ap.has_previous%} disabled{%endif%}"><a href="{%if ap.has_previous%}{% url 'apsnmp' ap.previous_page_number %}?order={{order}}{%else%}#{%endif%}">Previous</a></li>
		<li class="next{%if not ap.has_next%} disabled{%endif%}"><a href="{%if ap.has_next%}{% url 'apsnmp' ap.next_page_number %}?order={{order}}{%else%}#{%endif%}">Next</a></li>
	</ul>
 	{%endif%}
</footer>
{%endblock%}

netwObserver/gatherer/templates/gatherer/dhcplogs.html
{% extends "gatherer/logs.html" %}
{% load staticfiles %}
{% load gatherer_extra_tags %}

{%block logs%}
<table class="table table-striped table-hover">
	<thead>
		<tr>
			<th></th>
			<th>Date</th>
			<th>DHCP Server</th>
			<th>Type</th>
			<th>IP</th>
			<th>Device</th>
		</tr>
	</thead>
	<tbody>
		{% for event in dhcpEvent %}
		<tr {% if event.dhcpType == 'ack' %}class="success"{% elif event.dhcpType == 'inf' %}class="info"{%elif event.dhcpType == 'dis' and event.message %}class="warning" data-toggle="tooltip" data-placement="bottom" title="{{event.message}}"{%elif event.dhcpType == 'log'%}class='info' data-toggle="tooltip" data-placement="bottom" title="{{event.message}}"{%endif%}>
			<th>{%if event.dhcpType == 'dis' and event.message %}<span class="glyphicon glyphicon-warning-sign"></span>{%endif%}</th>
			<td>{{event.date|date:"D d M Y H:i:s"}}:{{event.microsecond}}</td>
			<td>{{event.server}}</td>
			<td>{{event.get_dhcpType_display}}</td>
			<td>{{event.ip|default_if_none:"-"}}</td>
			<td>{{event.device}}</td>
		</tr>
		{% endfor %}
	</tbody>
</table>

<footer>
	{{dhcpEvent|length}} entr{{ dhcpEvent|pluralize:'y,ies' }}
	{%if dhcpEvent.paginator.num_pages > 1 %}
	<p class="text-center">Page {{ dhcpEvent.number }} of {{ dhcpEvent.paginator.num_pages }}</p>
	<ul class="pager">
		<li class="previous{%if not dhcpEvent.has_previous%} disabled{%endif%}"><a href="{%if dhcpEvent.has_previous%}{% url 'dhcplogs' dhcpEvent.previous_page_number %}{%else%}#{%endif%}">Newer</a></li>
		<li class="next{%if not dhcpEvent.has_next%} disabled{%endif%}"><a href="{%if dhcpEvent.has_next%}{% url 'dhcplogs' dhcpEvent.next_page_number %}{%else%}#{%endif%}">Older</a></li>
	</ul>
	{%endif%}
</footer>
{%endblock%}

netwObserver/gatherer/templates/gatherer/logs.html
{% extends "common/base.html" %}
{% load staticfiles %}
{% load gatherer_extra_tags %}
{% block custCSS %}
<link href="{% static 'gatherer/css/index.css' %}" rel="stylesheet">
{% endblock %}


{% block content %}

<ul class="nav nav-tabs">
	<li><a href="{% url 'index' %}">General</a></li>
	<li class="active"><a href="#">Logs</a></li>
	<li><a href="{% url 'snmp' %}">SNMP</a></li>
</ul>

<div class='row' style="margin-top: 2px;">
	<div class="col-md-2">
		<ul class="nav nav-pills nav-stacked">
			<li {% if cat == 'dhcp' %}class="active"{%endif%}><a href="{% url 'dhcplogs' %}">DHCP</a></li>
			<li {% if cat == 'radius' %}class="active"{%endif%}><a href="{% url 'radiuslogs' %}">Radius</a></li>
			<li {% if cat == 'wism' %}class="active"{%endif%}><a href="{% url 'wismlogs' %}">Wism</a></li>
		</ul>
	</div>

	<div class="col-md-10">
		{%block logs%}

		
		{%endblock%}
	</div>

</div>


{% endblock %}

netwObserver/gatherer/templates/gatherer/mssnmp.html
{% extends "gatherer/snmp.html" %}
{% load staticfiles %}

{%block category%}
<table class="table table-striped table-hover">
	<thead>
		<tr>
			<th><a href="{% url 'msrefresh' %}"><span class="glyphicon glyphicon-refresh"></span></a></th>
			<th>Mac Address</th>
			<th>IP</th>
			<th>SSID</th>
			<th>Wifi Protocol</th>
		</tr>
	</thead>
	<tbody>
		{% for station in ms %}
		<tr>
			<td></td>
			<td>{{station.macAddress}}</td>
			<td>{{station.ip}}</td>
			<td>{{station.ssid}}</td>
			<td>{{station.get_dot11protocol_display}}</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
<footer>
	{{ms|length}} entr{{ ms|pluralize:'y,ies' }}
	{%if ms.paginator.num_pages > 1 %}
	<p class="text-center">Page {{ ms.number }} of {{ ms.paginator.num_pages }}</p>
	<ul class="pager">
		<li class="previous{%if not ms.has_previous%} disabled{%endif%}"><a href="{%if ms.has_previous%}{% url 'mssnmp' ms.previous_page_number %}{%else%}#{%endif%}">Previous</a></li>
		<li class="next{%if not ms.has_next%} disabled{%endif%}"><a href="{%if ms.has_next%}{% url 'mssnmp' ms.next_page_number %}{%else%}#{%endif%}">Next</a></li>
	</ul>
	{%endif%}
</footer>
{%endblock%}

netwObserver/gatherer/templates/gatherer/wismlogs.html
{% extends "gatherer/logs.html" %}
{% load staticfiles %}
{% load gatherer_extra_tags %}

{%block logs%}

<table class="table table-striped table-hover">
	<thead>
		<tr>
			<th></th>
			<th>Date</th>
			<th>IP</th>
			<th>Category</th>
			<th>Severity</th>
			<th>Mnemo</th>
		</tr>
	</thead>
	<tbody>
		{% for event in wismEvent %}
			<tr 
			{%if event.severity <= 2 %}
			class='danger'>
				<td><span class="glyphicon glyphicon-fire"></span></td>
				
			{%elif event.severity <= 4 %}
			class='warning'>
				<td><span class="glyphicon glyphicon-warning-sign"></span></td>
				
			{%elif event.severity <= 5 %}
			class='info'>
				<td><span class="glyphicon glyphicon-eye-open"></span></td>
				
			{%else%}
			>
				<td></td>
			{%endif%}
				<td>{{event.date|date:"D d M Y H:i:s"}}:{{event.microsecond}}</td>
				<td>{{event.wismIp}}</td>
				<td>{{event.category}}</td>
				<td data-toggle="tooltip" data-placement="bottom" title="{{event.get_severity_display}}">{{event.severity}}</td>
				<td data-toggle="tooltip" data-placement="bottom" title="{{event.message}}">{{event.mnemo}}</td>
			</tr>
		{% endfor %}
	</tbody>
</table>
<footer>
	{{wismEvent|length}} entr{{ wismEvent|pluralize:'y,ies' }}
	{%if wismEvent.paginator.num_pages > 1 %}
	<div class="text-center">Page {{ wismEvent.number }} of {{ wismEvent.paginator.num_pages }}</div>
	<ul class="pager">
		<li class="previous{%if not wismEvent.has_previous%} disabled{%endif%}"><a href="{%if wismEvent.has_previous%}{% url 'wismlogs' wismEvent.previous_page_number %}{%else%}#{%endif%}">Newer</a></li>
		<li class="next{%if not wismEvent.has_next%} disabled{%endif%}"><a href="{%if wismEvent.has_next%}{% url 'wismlogs' wismEvent.next_page_number %}{%else%}#{%endif%}">Older</a></li>
	</ul>
	{%endif%}
</footer>

{%endblock%}